### ISSUE TITLE
Fazer deploy da aplicação no fly.io

### ISSUE THREAD

**Issue by joaogdfaero** [joaogdfaero/CargoMatch#44]
https://www.youtube.com/watch?v=F4xnGutoRAs

Bug do PostgreSQL não rodar, possíveis soluções:

`rails aborted! ActiveRecord::ConnectionNotEstablished: connection to server at "127.0.0.1", port 5432 failed: Connection refused Is the server running on that host and accepting TCP/IP connections? Caused by: PG::ConnectionBad: connection to server at "127.0.0.1", port 5432 failed: Connection refused Is the server running on that host and accepting TCP/IP connections?`

https://stackoverflow.com/questions/37307346/is-the-server-running-on-host-localhost-1-and-accepting-tcp-ip-connections

**Comment by joaogdfaero** [comment]
Pro comando `fly` funcionar no terminal precisa rodar:

`source ~/.bash_profile`

**Comment by joaogdfaero** [comment]
Closed with #46 #48 

Deploy feito em:
https://cargomatch.fly.dev/

**Comment by joaogdfaero** [comment]
LOGS BUG DEPLOY:

`--> Building image done
==> Pushing image to fly
The push refers to repository [registry.fly.io/cargomatch]
6edf29e7d9ae: Pushed 
db15fdb0c257: Pushed 
728b31e45fb0: Pushed 
9abddead4cbc: Pushed 
62de5462efe2: Pushed 
ef177ce47746: Pushed 
4c38ebe47533: Pushed 
136727c59bb2: Pushed 
0891caaa0e93: Pushed 
a953c9322cfb: Pushed 
d0fd44b642b8: Pushed 
025a544a4685: Pushed 
511780f88f80: Pushed 
deployment-01H807Z2GSJXN17KRG04WZ7PZR: digest: sha256:52b0ba0cf460913e353955e165cc28ff21e835cf50292992cd7bebd964c3af6a size: 3054
--> Pushing image done
image: registry.fly.io/cargomatch:deployment-01H807Z2GSJXN17KRG04WZ7PZR
image size: 551 MB

Watch your deployment at https://fly.io/apps/cargomatch/monitoring

Provisioning ips for cargomatch
  Dedicated ipv6: 2a09:8280:1::2d:1858
  Shared ipv4: 66.241.124.234
  Add a dedicated ipv4 with: fly ips allocate-v4

Running cargomatch release_command: ./bin/rails db:prepare
  Waiting for 328744d4a06098 to get exit event
Error release_command failed running on machine 328744d4a06098 with exit code 1.
Check its logs: here's the last 100 lines below, or run 'fly logs -i 328744d4a06098':
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `new_connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:700:in `checkout_new_connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:679:in `try_to_checkout_new_connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:640:in `acquire_connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:341:in `checkout'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_handler.rb:211:in `retrieve_connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_handling.rb:313:in `retrieve_connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_handling.rb:280:in `connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:196:in `block in prepare_all'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:557:in `block (2 levels) in each_current_configuration'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:554:in `each'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:554:in `block in each_current_configuration'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:553:in `each'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:553:in `each_current_configuration'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:191:in `prepare_all'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/railties/databases.rake:391:in `block (2 levels) in <main>'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
  /rails/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-5.10.0/lib/sentry/rake.rb:26:in `execute'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
  /rails/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
  /rails/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
  /rails/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
  /rails/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/command.rb:51:in `invoke'
  /rails/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<main>'
  /rails/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  /rails/bin/rails:4:in `<main>'
  Caused by:
  PG::ConnectionBad: connection to server at "127.0.0.1", port 5432 failed: Connection refused
  	Is the server running on that host and accepting TCP/IP connections?
  /rails/vendor/bundle/ruby/3.1.0/gems/pg-1.5.3/lib/pg/connection.rb:696:in `async_connect_or_reset'
  /rails/vendor/bundle/ruby/3.1.0/gems/pg-1.5.3/lib/pg/connection.rb:824:in `connect_to_hosts'
  /rails/vendor/bundle/ruby/3.1.0/gems/pg-1.5.3/lib/pg/connection.rb:759:in `new'
  /rails/vendor/bundle/ruby/3.1.0/gems/pg-1.5.3/lib/pg.rb:63:in `connect'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:78:in `new_client'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `public_send'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `new_connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:700:in `checkout_new_connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:679:in `try_to_checkout_new_connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:640:in `acquire_connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:341:in `checkout'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_handler.rb:211:in `retrieve_connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_handling.rb:313:in `retrieve_connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_handling.rb:280:in `connection'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:196:in `block in prepare_all'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:557:in `block (2 levels) in each_current_configuration'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:554:in `each'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:554:in `block in each_current_configuration'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:553:in `each'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:553:in `each_current_configuration'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:191:in `prepare_all'
  /rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/railties/databases.rake:391:in `block (2 levels) in <main>'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
  /rails/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-5.10.0/lib/sentry/rake.rb:26:in `execute'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
  /rails/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
  /rails/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
  /rails/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
  /rails/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
  /rails/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/command.rb:51:in `invoke'
  /rails/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<main>'
  /rails/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  /rails/bin/rails:4:in `<main>'
  Tasks: TOP => db:prepare
  (See full trace by running task with --trace)
   INFO Main child exited normally with code: 1
   INFO Starting clean up.
   WARN hallpass exited, pid: 266, status: signal: 15 (SIGTERM)
  2023/08/16 22:41:36 listening on [fdaa:2:cbdc:a7b:e3:a8fb:6f68:2]:22 (DNS: [fdaa::3]:53)
  [    3.300571] reboot: Restarting system
  machine restart policy set to 'no', not restarting
Error: release command failed - aborting deployment. error release_command machine 328744d4a06098 exited with non-zero status of 1
`

**Comment by joaogdfaero** [comment]
Closed with #51
